
import Head from 'next/head'
import Link from 'next/link';
export async function getServerSideProps() {
  // Fetch data from the API
  const res = await fetch('https://gsmarena-three.vercel.app/');
  const cetegories = await res.json();
  console.log(cetegories);
  // Pass data to the page component as props
  return {
    props: { cetegories }
  };
}



export default function Home({ cetegories }) {
  console.log(cetegories);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className="grid grid-cols-3 gap-5 p-12 bg-gray-200">
          {
            cetegories.map((cetegory, idx) => {
              return (
                <div key={idx}>
                  <div className="bg-white shadow-md rounded-md overflow-hidden">
                    <Link className="block p-4 text-gray-800 hover:text-white hover:bg-gray-800 transition-all"
                      href={{
                        pathname: '/brand/[slug]',
                        query: { slug: cetegory?.slug },
                      }}
                    >

                      <h4 className="text-lg font-medium">{cetegory?.brandname}</h4>
                      <p className="text-sm text-gray-600">({cetegory?.count})</p>

                    </Link>
                  </div>
                </div>
              )
            })
          }
        </div>
      </main>
    </>
  )
}
